language: node_js
node_js:
  - "0.12"
before_install:
  - "curl -L https://raw.githubusercontent.com/arunoda/travis-ci-laika/master/configure.sh | /bin/sh"
services:
  - mongodb
env:
  - LAIKA_OPTIONS="-t 5000"
addons:
    code_climate:
        repo_token: b116c62ff778252c23e3cef2cf58255e6855b18305d5e9afd29fabe17e5eb9de